In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('18_energy_regression_dataset.csv')

In [3]:
print(dataset.shape)
print(dataset.head(5))

(9568, 5)
      AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90


In [4]:
x=dataset.iloc[:,:-1].values
x

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [5]:
y=dataset.iloc[:,-1].values
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [6]:
ysvm=y.reshape(len(y),1)
ysvm

array([[463.26],
       [444.37],
       [488.56],
       ...,
       [429.57],
       [435.74],
       [453.28]])

In [7]:
'''train test split'''
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
x_trainsvm,x_testsvm,y_trainsvm,y_testsvm=train_test_split(x,ysvm,test_size=0.25,random_state=0)


In [8]:
'''Importing ML ALG'''
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR 



In [9]:
'''INITIALIZING DIFF REGRESSION ALG'''
from sklearn.preprocessing import StandardScaler

modelLR=LinearRegression()

poly_reg=PolynomialFeatures(degree=4)
x_poly=poly_reg.fit_transform(x_train)
modelPLR=LinearRegression()

modelRFR=RandomForestRegressor(n_estimators=10,random_state=0)

modelDTR=DecisionTreeRegressor(random_state=0)

modelSVR=SVR(kernel='rbf')

sc_x=StandardScaler()
sc_y=StandardScaler()
x_trainsvm=sc_x.fit_transform(x_trainsvm)
y_trainsvm=sc_y.fit_transform(y_trainsvm)


In [10]:
'''TRAINING REGRESSION ALG'''
modelLR.fit(x_train, y_train)
modelPLR.fit(x_poly, y_train)
modelRFR.fit(x_train, y_train)
modelDTR.fit(x_train, y_train)
modelSVR.fit(x_trainsvm, y_trainsvm)

D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

In [11]:
'''PREDICTING TEST SET FOR VALIDATION'''
modelLRy_pred  = modelLR.predict(x_test)
modelPLRy_pred = modelPLR.predict(poly_reg.transform(x_test))
modelRFRy_pred = modelRFR.predict(x_test)
modelDTRy_pred = modelDTR.predict(x_test)
modelSVRy_pred = sc_y.inverse_transform(modelSVR.predict(sc_x.transform(x_test)))

In [12]:
'''EVALUATING MODEL PERFORMANCE'''
from sklearn.metrics import r2_score
print("Linear Regression Accuracy: {}".format(r2_score(y_test, modelLRy_pred)))
print("Polynomial Regression Accuracy: {}".format(r2_score(y_test, modelPLRy_pred)))
print("Random Forest Regression Accuracy: {}".format(r2_score(y_test, modelRFRy_pred)))
print("Decision Treee Regression Accuracy: {}".format(r2_score(y_test, modelDTRy_pred)))
print("Support Vector Regression Accuracy: {}".format(r2_score(y_test, modelSVRy_pred)))

Linear Regression Accuracy: 0.9323789104734466
Polynomial Regression Accuracy: 0.9459731226546759
Random Forest Regression Accuracy: 0.960853142550123
Decision Treee Regression Accuracy: 0.9229733351311707
Support Vector Regression Accuracy: 0.9483940635883192
